import 'package:assign_erp/core/util/str_util.dart';
import 'package:hive/hive.dart';

// use this CMD: dart run build_runner build
part 'cache_data_model.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 0)
class CacheData extends HiveObject {
  /// [id] expect `String`
  @HiveField(0)
  late String id;

  /// [data] expect `Map<String, dynamic>`
  @HiveField(1)
  late Map<String, dynamic> data;

  CacheData({required this.id, required this.data});

  /// fromGeneric / fromJson Function [CacheData.fromMap]
  factory CacheData.fromMap(Map<String, dynamic> data, {String? documentId}) =>
      CacheData(id: documentId ?? data['id'], data: data);

  /// fromCache Function [CacheData.fromCache]
  factory CacheData.fromCache(Map<String, dynamic> data, String documentId) =>
      CacheData(id: documentId, data: data['data']);

  bool get isEmpty => id.isNullOrEmpty || data.isEmpty || data.entries.isEmpty;
}
