import 'package:hive/hive.dart';

// dart run build_runner build
part 'setup_printout_model.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 1)
class SetupPrintOut extends HiveObject {
  @HiveField(0)
  final String layout;
  @HiveField(1)
  final String footerColor;
  @HiveField(2)
  final String headerColor;
  @HiveField(3)
  final List<String> paletteColor;
  @HiveField(4)
  final String? companyLogo;
  @HiveField(5)
  final String? companyName;
  @HiveField(6)
  final String? companyEmail;
  @HiveField(7)
  final String? companyPhone;
  @HiveField(8)
  final String? companyAddress;
  @HiveField(9)
  final String? companyFax;

  SetupPrintOut({
    this.layout = 'dense',
    this.footerColor = '#ff2196f3',
    this.headerColor = '#ff4caf50',
    this.paletteColor = const [],
    this.companyLogo,
    this.companyName,
    this.companyEmail,
    this.companyPhone,
    this.companyAddress,
    this.companyFax,
  });

  // Check for all empty fields
  bool get isEmpty =>
      layout == '' &&
          (paletteColor.isEmpty || paletteColor.contains('[]')) &&
          headerColor == '' &&
          footerColor == '' &&
          companyLogo == '';

  bool get isNotEmpty => !isEmpty;

  // Check for empty layout
  bool get isLayoutEmpty => layout == '';

  // Check for empty colors fields
  bool get isColorsEmpty =>
      (paletteColor.isEmpty || paletteColor.contains('[]')) &&
          headerColor == '' &&
          footerColor == '';

  String get asString =>
      '$layout -> $paletteColor -> $headerColor -> $footerColor';

  SetupPrintOut copyWith({
    String? layout,
    String? headerColor,
    String? footerColor,
    List<String>? paletteColor,
    String? companyLogo,
    String? companyName,
    String? companyEmail,
    String? companyPhone,
    String? companyAddress,
    String? companyFax,
  }) =>
      SetupPrintOut(
        layout: layout ?? this.layout,
        headerColor: headerColor ?? this.headerColor,
        footerColor: footerColor ?? this.footerColor,
        paletteColor: paletteColor ?? this.paletteColor,
        companyLogo: companyLogo ?? this.companyLogo,
        companyName: companyName ?? this.companyName,
        companyEmail: companyEmail ?? this.companyEmail,
        companyPhone: companyPhone ?? this.companyPhone,
        companyAddress: companyAddress ?? this.companyAddress,
        companyFax: companyFax ?? this.companyFax,
      );
}