// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxJol8pf9-VSpWqq73FLcjiQgT8WTm5ik',
    appId: '1:314979320905:web:55596765b4024e8ae46b98',
    messagingSenderId: '314979320905',
    projectId: 'assign-erp',
    authDomain: 'assign-erp.firebaseapp.com',
    storageBucket: 'assign-erp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKbYNavXV-NIYj1sDEYVK5Hua-Uc0XaLQ',
    appId: '1:314979320905:android:99af7c5b704258c0e46b98',
    messagingSenderId: '314979320905',
    projectId: 'assign-erp',
    storageBucket: 'assign-erp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlYLz2vIN8A035zilNePr4jt9Zmnj50FQ',
    appId: '1:314979320905:ios:c5e9ecae21be7802e46b98',
    messagingSenderId: '314979320905',
    projectId: 'assign-erp',
    storageBucket: 'assign-erp.firebasestorage.app',
    iosBundleId: 'com.assigndevelopers.erp.assignErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlYLz2vIN8A035zilNePr4jt9Zmnj50FQ',
    appId: '1:314979320905:ios:c5e9ecae21be7802e46b98',
    messagingSenderId: '314979320905',
    projectId: 'assign-erp',
    storageBucket: 'assign-erp.firebasestorage.app',
    iosBundleId: 'com.assigndevelopers.erp.assignErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxJol8pf9-VSpWqq73FLcjiQgT8WTm5ik',
    appId: '1:314979320905:web:62b131983a13daf9e46b98',
    messagingSenderId: '314979320905',
    projectId: 'assign-erp',
    authDomain: 'assign-erp.firebaseapp.com',
    storageBucket: 'assign-erp.firebasestorage.app',
  );

}